apiVersion: v1
kind: Pod
metadata:
  name: pod-local
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc-local
  containers:
    - name: pod-hostpath-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/teste"
          name: task-pv-storage